//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Refactoring {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Refactoring.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your balance is {0}.
        /// </summary>
        public static string msgBalance {
            get {
                return ResourceManager.GetString("msgBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Password:.
        /// </summary>
        public static string msgEnterPassword {
            get {
                return ResourceManager.GetString("msgEnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Username:.
        /// </summary>
        public static string msgEnterUsername {
            get {
                return ResourceManager.GetString("msgEnterUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press Enter key to exit.
        /// </summary>
        public static string msgExit {
            get {
                return ResourceManager.GetString("msgExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You entered an invalid password..
        /// </summary>
        public static string msgIncorrectPassword {
            get {
                return ResourceManager.GetString("msgIncorrectPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have enough money to buy that..
        /// </summary>
        public static string msgInsufficientFunds {
            get {
                return ResourceManager.GetString("msgInsufficientFunds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, only {0} {1} available.
        /// </summary>
        public static string msgInsufficientStock {
            get {
                return ResourceManager.GetString("msgInsufficientStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid quantity.
        /// </summary>
        public static string msgInvalidQuantity {
            get {
                return ResourceManager.GetString("msgInvalidQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid selection.
        /// </summary>
        public static string msgInvalidSelection {
            get {
                return ResourceManager.GetString("msgInvalidSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You entered an invalid user..
        /// </summary>
        public static string msgInvalidUser {
            get {
                return ResourceManager.GetString("msgInvalidUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login successful! Welcome {0}!.
        /// </summary>
        public static string msgLoginSuccessful {
            get {
                return ResourceManager.GetString("msgLoginSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Exit.
        /// </summary>
        public static string msgMenuExit {
            get {
                return ResourceManager.GetString("msgMenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your new balance is {0}.
        /// </summary>
        public static string msgNewBalance {
            get {
                return ResourceManager.GetString("msgNewBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, {0} is out of stock.
        /// </summary>
        public static string msgOutOfStock {
            get {
                return ResourceManager.GetString("msgOutOfStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You bought {0} {1}.
        /// </summary>
        public static string msgPurchased {
            get {
                return ResourceManager.GetString("msgPurchased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You want to buy:.
        /// </summary>
        public static string msgWantToBuy {
            get {
                return ResourceManager.GetString("msgWantToBuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to TUSC / Bienvenue à LCSC.
        /// </summary>
        public static string msgWelcome {
            get {
                return ResourceManager.GetString("msgWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a number:.
        /// </summary>
        public static string promptEnterNumber {
            get {
                return ResourceManager.GetString("promptEnterNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter amount to purchase:.
        /// </summary>
        public static string promptPurchaseAmount {
            get {
                return ResourceManager.GetString("promptPurchaseAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What would you like to buy?.
        /// </summary>
        public static string promptWhatToBuy {
            get {
                return ResourceManager.GetString("promptWhatToBuy", resourceCulture);
            }
        }
    }
}
